<a href="https://colab.research.google.com/github/edwardsnj/pride-study-retrieval-cofest-2026/blob/main/notebooks/TextEmbedding%2BTFIDF_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#
# Import necessary modules
#

import sys, os, httpimport

with httpimport.github_repo("EdwardsLabProjects", "pride-study-retrieval-cofest-2026", ref="main"):
    from notebooks.lib import *

set_random_seed(state=None)

Version: 1.0.34
Using random seed: 7091794

In [2]:
#
# Get embeddings and known true positives
#

md,emb = embeddings("openai-3-small")
embdim = emb.shape[0]
tp,tn = knownstudies()

allacc = set(emb.columns)
tp &= allacc
tn &= allacc

assert len(tp & tn) == 0, "TP and TN should not intersect!"

# Print out some details...
print(f"Embeddings: {emb.shape}")
print(f"True Pos: {len(tp)}")
print(f"True Neg: {len(tn)}")

# allacc,avgemb = select_by_embedding_proximity(tp,emb,1000)
# print(f"All Acc: {len(allacc)}")

Embeddings: (1536, 36696)
True Pos: 86
True Neg: 47

In [3]:
#
# Create train/test split
#
TESTFRAC = 0.2
BACKGROUND_OVERSAMPLE = 25

train_acc, train_y, test_acc, test_y = split_train_test(allacc, tp, tn,
    test_size=TESTFRAC, bgsize=BACKGROUND_OVERSAMPLE)

print(f"\nTrain set size: {len(train_acc)}")
print(f"  True Positives in Train: {train_y.count(1)}")
print(f"  True Negatives in Train: {train_y.count(0)}")

print(f"\nTest set size: {len(test_acc)}")
print(f"  True Positives in Test: {test_y.count(1)}")
print(f"  True Negatives in Test: {test_y.count(0)}")

Train set size: 1788
  True Positives in Train: 68
  True Negatives in Train: 1720

Test set size: 448
  True Positives in Test: 18
  True Negatives in Test: 430

In [4]:
# Build the TF-IDF features from train data only,
# but build feature vectors for all documents

from sklearn.feature_extraction import text
stop_words = list(set(list(text.ENGLISH_STOP_WORDS) + """

""".split()))

tfidf_extra_args = dict(positive_only=False, # Use only positive set for word selection
                        min_df=1, # minimum documents word is in
                        max_df=1.0, # maximum documents word is in
                        max_features=None, # max number of words to use
                        stop_words=stop_words) # words to ignore

tfidf,tfidf_model = create_tfidf_features(md, train_acc, train_y,
                                          test_acc, **tfidf_extra_args)

print(f"TF-IDF features shape: {tfidf.shape}")

TF-IDF features shape: (35422, 2236)

In [5]:
logreg_extra_args = dict(class_weight='balanced',C=10.0,
                         penalty='l1', solver='liblinear',
                         use_embed=True, use_tfidf=True)
trained_model = train_document_classifier(emb, tfidf,
                                          train_acc, train_y,
                                          test_acc, test_y,
                                          **logreg_extra_args)
print("NZ Coeffs:",sum(*[1*(xi!=0) for xi in trained_model.coef_]))

Training data shape: (1788, 36958) (Positives: 68, Negatives: 1720)
Testing data shape: (448, 36958) (Positives: 18, Negatives: 430)

--- Model Evaluation ---
Accuracy: 0.9933

Classification Report:
                precision    recall  f1-score   support

Background (0)       1.00      0.99      1.00       430
 Seed-like (1)       0.86      1.00      0.92        18

      accuracy                           0.99       448
     macro avg       0.93      1.00      0.96       448
  weighted avg       0.99      0.99      0.99       448

NZ Coeffs: 44

In [6]:
nzemb,nztfidf,topfeat = top_features(trained_model,tfidf_model,nembed=embdim,**logreg_extra_args)
print(f"Number of sem. embedding dimensions with non-zero coefficients: {nzemb}")
print(f"Number of TF-IDF dimensions with non-zero coefficients: {nztfidf}")
print("\nTop Features:")
display(topfeat)

show_top_feature_examples(topfeat, md)

Number of sem. embedding dimensions with non-zero coefficients: 1
Number of TF-IDF dimensions with non-zero coefficients: 43

Top Features:

              Feature  Coefficient
27110          pngase   129.216335
12516     deamidation    38.708530
34018             tof   -33.514452
17071       glycosite    22.172386
17078   glycosylation    17.695359
12672  deglycosylated    16.360529
7748              asn    14.317433
17077    glycosylated    13.482632
9356               bx    13.425159
17887   hepatobiliary   -13.311078
33716    thermophilic    13.231471
24413            nmpo    13.160786
33004           swath   -12.821566
9691              car   -12.602497
8316          basigin     9.466818
16988         glycans     9.054372
20383            kegg     8.822617
29797            rfix     8.304861
17197           gpibα     8.105124
17054   glycoproteins     8.037122
8022          autocsc     7.755468
21208     liraglutide     7.688693
25961             pbs     7.201300
29885            rice     5.907061
32923         surface     5.648582
9904       categories     5.623098
6685              agp     5.076066
333         embed_333     3.889309
18141            hku1    -3.633110
16986          glycan     3.087702
14886            ero1     3.023842
11978           csf3r    -3.019908
30626          scehcd    -2.860025
10652       circadian    -2.525451
15625         fcgriia     2.361103
16933            gluc     2.153956
32058           spike     2.043095
36795              µl     2.033897
16379           furin     1.386759
15467             fab     1.299577
36930              μl    -0.857604
20715     lactalbumin    -0.772387
18921             il6     0.281147
2848              18o     0.132069

=== 'pngase' (coef: +129.2163) ===
  PXD001432: The beads were washed with 40 µl 1 x G7 buffer (NEB, Frankfurt a.M., Germany) and then incubated with 20 µl 1x G7 buffer containing 500 U glyerol-free PNGase F (NEB) at 37 °C in a thermomixer for 6 h to release the glycopeptides from the beads.
  PXD010911: 1 μL (500 units) of PNGase F was added to one tube of peptides in each pair of aliquots; the second tube was not treated with the glycosidase and served as the control.
  PXD007267: The EndoH released glycans were removed by centrifugation and the remaining material was exchanged into 40 mM ammonium bicarbonate buffer in H2[18O] (Sigma), and subsequently digested with 100 units of N-glycosidase F (PNGaseF, Roche) dissolved in H2[18O].
  PXD007268: Aliquots of the eluted Ricin‐bound and ConA‐bound fractions were independently subjected to EndoH followed by PNGaseF digestion (Roche Applied Science), subjected to SDS–PAGE and the gel lanes were then divided into 10 independent slices.
  PXD005726: After an initial incubation at 37 °C for 24 h, the samples were speed-vac dried and PNGase F (1:200) was added together with 18O water to identify N-linked glycosylation sites by isotopic mass-differences in the MS analysis.

=== 'deamidation' (coef: +38.7085) ===
  PXD000047: Structure modifications allowed were oxidized methionine, and deamidation of asparagine and glutamine residues, which were searched as variable modifications.
  PXD001252: Variable  modiﬁcations  were  oxidation  (M),  acetylation  of  protein  N-terminus,  deamidation  (NQ)  and  phosphorylation (ST).
  PXD002591: Cysteine carbamidomethylation was set as fixed modification, while methionine oxidation, asparagine and glutamine deamidation, serine, threonine and asparagine (Asn) N-acetylhexosamine (HexNAc) were set as variable modifications.
  PXD001204: Sequest search parameters included two maximum enzyme miscleavages; precursor mass tolerance of 10 ppm; fragment mass tolerance of 0.8 Da; dynamic modifications (see Supplemental Table S1) of mono oxidation to Lys, Arg, Pro, Thr, Met, His, Tyr, Ala, Asn, Asp, Glu, Gln, Ile, Leu, Phe, Ser and Val (Ox, +15.995 Da), dioxidation to Lys, Arg, Pro, His, Tyr, Asn, Asp, Phe and Met (DiOx, + 31.990 Da), carbonylation to Lys, Arg, Pro, Glu, Gln, Leu, Ser, Val and Ile (+13.979 Da), deamidation to Gln, Arg and Asn (0.984 Da), decarboxylation to Asp and Glu (-30.010 Da), oxidation of His to Asn (-23.0159 Da) or Asp (-22.032 Da) or aspartylurea (-10.032 Da) or ring open (4.979 Da), carbonylation of Arg to glutamic semialdehyde (GluSA, -43.053 Da), Lys to aminoadipic semialdehyde (AminoAdSA, -1.032 Da) or aminoadipic acid (14.963 Da), Pro to pyrrolidinone (-30.010 Da), and Thr to 2-amino-3-oxo-butanoic acid (Oxd’n, -2.016 Da).
  PXD015857: All searches were performed employing the following search parameters: trypsin as digestion enzyme, maximum missed cleavages, 2; precursor ion mass tolerance ± 10 ppm, fragment ion tolerance ±0.1 Da; fixed modifications: carbamidomethylation of cysteine; variable modifications: deamidation of asparagine and glutamine, oxidation of methionine; Peptide Spectrum Matches, peptides and proteins were validated at a 1.0% False Discovery Rate estimated using the decoy hit distribution.

=== 'tof' (coef: -33.5145) ===
  PXD000027: # maize leaf ESI-Q-TOF MS -  Comparative analysis of salt-responsive phosphoproteins in maize leaves using Ti(4+)--IMAC enrichment and ESI-Q-TOF MS
  PXD012013: Proteins were subjected to standard tryptic digestion protocol, and global proteomic analysis was performed using an Agilent 6550 iFunnel Q-TOF mass spectrometer (Agilent Technologies, Santa Clara, CA) coupled to an Agilent 1290 UHPLC system.
  PXD002644: Protein extracts from spleen were subjected to 2D-DiGE and MS-MALDI-TOF/TOF analysis to identify proteins that were differentially expressed in CD38 KO and B6 WT mice with arthritis, with inflammation, or non-immunized.
  PXD001247: We performed protein digestion according to a filter-aided sample preparation (FASP) protocol using a 10 kDa molecular weight cutoff filter (EMD Millipore).
  PXD001268: PeptideProphet calculates false-positive error rates at specific probability score cutoff values for each data set.18 A minimum PeptideProphet probability score of ≥0.5 was used to remove low probability peptides.

=== 'glycosite' (coef: +22.1724) ===
  PXD024196: PGC separation is shown to selectively retain shorter, more hydrophilic glycopeptide species, imparting higher average charge, and exhibiting greater microheterogeneity coverage for identified glycosites.
  PXD013764: We found 1697 glycopeptides from 110 glycoproteins and 191 glycosites of which 43 novel sites were not yet reported in experimental evidence.
  PXD018914: Interrogating the role of O-GlcNAc on a target protein in cells is critical yet challenging without disturbing O-GlcNAc globally or after extensive glycosite mapping.
  PXD022347: Interrogating the role of O-GlcNAc on a target protein in cells is critical yet challenging without disturbing O-GlcNAc globally or after extensive glycosite mapping.
  PXD027333: Singly modified glycopeptides assigned from EThCD spectra passing a 1% FDR and possessing a delta modification score of greater than or equal to ten were considered unambiguous glycosites.

=== 'glycosylation' (coef: +17.6954) ===
  PXD002644: # Identification of multiple transferrin species in spleen from mice with collagen-induced arthritis which may reflect changes in transferrin glycosylation associated with the disease activity.
  PXD002591: Asn(N) was used considering the low activity of PNGNase F in de-N-glycosylation(43).
  PXD008855: Due to the high degree of glycosylation by glycosaminoglycan (GAG), N-glycan and mucin-type O-glycan classes, the peptide sequence coverage of complex proteoglycans is revealed poorly by standard mass spectrometry-based proteomics methods.
  PXD010911: # Human Serum Immunoglobulin N-Glycosylation using nLC-MS/MS
  PXD002491: Additionally, galactosylation and glucosylgalactosylation of lysine, glycosylation of proline, conversion of N-terminal Glu and Gln to pyro-glutamate and deamidation of asparagine and glutamine were also set as variable modifications.

=== 'deglycosylated' (coef: +16.3605) ===
  PXD007267: After overnight incubation at 37 oC, the PNGaseF released glycans were removed by centrifugation and the deglycosylated proteins were diafiltered into 40 mM ammonium bicarbonate and subsequently digested with a mixture of 1:100 (enzyme: substrate) Lys-C and 1:20 trypsin (Roche) at 37 oC for 48 h.
  PXD005726: Then proteins were resuspended in deglycosylation buffer (25 mM EDTA, 50 mM sodium acetate, 50 mM Tris, pH 6.8) and deglycosylated using the following deglycosylation enzymes (chondroitinase ABC (1:100), keratinase (1:500), heparinase II (1:500), α2-3,6,8,9-neuraminidase (1:200), ß-N-acetylglucosaminidase (1:200) and O-glycosidase (1:200)).
  PXD002849: Enriched glycopeptide samples were deglycosylated using PNGase A and F enzymes.
  PXD003299: Isolated rat canalicular membrane vesicles were stripped from adhering proteins, deglycosylated and protease digested before shot gun proteomic analysis.
  PXD003498: Virus samples were deglycosylated and subjected to C18 LC-MS/MS for proteomics.

=== 'asn' (coef: +14.3174) ===
  PXD002591: Cysteine carbamidomethylation was set as fixed modification, while methionine oxidation, asparagine and glutamine deamidation, serine, threonine and asparagine (Asn) N-acetylhexosamine (HexNAc) were set as variable modifications.
  PXD001204: Sequest search parameters included two maximum enzyme miscleavages; precursor mass tolerance of 10 ppm; fragment mass tolerance of 0.8 Da; dynamic modifications (see Supplemental Table S1) of mono oxidation to Lys, Arg, Pro, Thr, Met, His, Tyr, Ala, Asn, Asp, Glu, Gln, Ile, Leu, Phe, Ser and Val (Ox, +15.995 Da), dioxidation to Lys, Arg, Pro, His, Tyr, Asn, Asp, Phe and Met (DiOx, + 31.990 Da), carbonylation to Lys, Arg, Pro, Glu, Gln, Leu, Ser, Val and Ile (+13.979 Da), deamidation to Gln, Arg and Asn (0.984 Da), decarboxylation to Asp and Glu (-30.010 Da), oxidation of His to Asn (-23.0159 Da) or Asp (-22.032 Da) or aspartylurea (-10.032 Da) or ring open (4.979 Da), carbonylation of Arg to glutamic semialdehyde (GluSA, -43.053 Da), Lys to aminoadipic semialdehyde (AminoAdSA, -1.032 Da) or aminoadipic acid (14.963 Da), Pro to pyrrolidinone (-30.010 Da), and Thr to 2-amino-3-oxo-butanoic acid (Oxd’n, -2.016 Da).
  PXD001340: MS/MS spectra collected via collision induced dissociation in the ion trap were searched against the concatenated target and decoy (reversed) Swiss-Prot and PIP4kγ  single entry protein databases using Sequest with differential modifications for Ser/Thr/Tyr phosphorylation (+79.97) and the sample processing artifacts Met oxidation (+15.99), deamidation of Asn and Gln (+0.984) and Cys alkylation (+57.029) as affixed modification.
  PXD002671: Met oxidation and Asn/Gln deamination were set as variable modifications.
  PXD002570: Carbamidomethylation of Cys was used as a fixed modification (except A1)  and oxidation of Met and deamidation of Asn and Gln as variable modifications.

=== 'glycosylated' (coef: +13.4826) ===
  PXD008855: Here, we developed a workflow to improve sequence coverage and identification of glycosylated peptides in proteoglycans.
  PXD001432: This led to the identification of 173 N-glycosylated surface proteins, of which 24 were previously not known to be expressed on human naive CD4+ T cells or have no defined role within T cell activation.
  PXD003911: It is highly glycosylated and parasite-derived immunogenic oligosaccharide motifs and glycoproteins are currently being investigated as novel vaccine candidates.
  PXD007267: After overnight incubation at 37 oC, the PNGaseF released glycans were removed by centrifugation and the deglycosylated proteins were diafiltered into 40 mM ammonium bicarbonate and subsequently digested with a mixture of 1:100 (enzyme: substrate) Lys-C and 1:20 trypsin (Roche) at 37 oC for 48 h.
  PXD005726: Then proteins were resuspended in deglycosylation buffer (25 mM EDTA, 50 mM sodium acetate, 50 mM Tris, pH 6.8) and deglycosylated using the following deglycosylation enzymes (chondroitinase ABC (1:100), keratinase (1:500), heparinase II (1:500), α2-3,6,8,9-neuraminidase (1:200), ß-N-acetylglucosaminidase (1:200) and O-glycosidase (1:200)).

=== 'bx' (coef: +13.4252) ===
  PXD013196: Here we show that USP9X and FBXW11 selectively regulate the stability of PTEN/ but not PTEN proteins by deubiqitination and ubiquitination respectively.
  PXD006158: # RIME against PBX1 protein in P19.6 mouse embryonal carcinoma cells treated for 48 hours with all-trans retinoic acid
  PXD013038: Notch; Signalling; Cell cycle; Fbxw7; Somitogenesis; Phosphorylation
  PXD004027: Preparations of recombinantly expressed GST-tagged ASK1-TIR1, HsCul1-MmRBX1 and AUX/IAAs proteins (either AtIAA6 or AtIAA19) from either SF9 insect cells or E.
  PXD007634: DDB1 and Cullins also serve as essential co-factor for accessory proteins encoded by other virus families like Vpr (HIV-1- and -2-encoded), Vpx (HIV-2-encoded), HBx (HBV-encoded) and its woodchuck hepatitis virus homolog (WHx).

=== 'hepatobiliary' (coef: -13.3111) ===
  PXD004476: The proteome analysis of bile fluid represents a promising strategy to identify biomarker candidates for various diseases of the hepatobiliary system.
  PXD028822: # Proteomic Analysis of Canine Hepatobiliary Neuroendocrine Neoplasms
  PXD036943: Multi-organ transcriptomic analysis revealed that serum EV-biomarkers were mostly expressed in hepatobiliary tissues, and scRNA-seq and immunofluorescence analysis of CCA tumors showed their presence mainly in malignant cholangiocytes.
  PXD037007: Multi-organ transcriptomic analysis revealed that serum EV-biomarkers were mostly expressed in hepatobiliary tissues, and scRNA-seq and immunofluorescence analysis of CCA tumors showed their presence mainly in malignant cholangiocytes.
  PXD013629: # Plasma Proteome for Hepatobiliary Carcinomas

In [7]:
results = score_all_studies(trained_model, emb, md, tfidf_model, train_acc, tp, tn)
display(results)

Scoring studies: 100%|##########| 74/74 [00:40<00:00,  1.81it/s]

,prideacc,title,probability,in_training,true_positive,true_negative
0,PXD031068,Secretome analysis of basidiomycetous yeast Ta...,1.0,False,False,False
1,PXD029218,Site-specific glycosylation patterns of SARS-C...,1.0,False,False,False
2,PXD060969,Identification and validation of protective gl...,1.0,False,False,False
3,PXD004361,HILIC and ERLIC Enrichment of Glycopeptides De...,1.0,True,True,False
4,PXD012589,Sweet and sour Ehrlichia: glycoproteomics and ...,1.0,False,True,False
...,...,...,...,...,...,...
36691,PXD029545,Quantitative phosphoproteomic analysis of Eime...,0.0,False,False,False
36692,PXD021653,Brain proteome analysis in Alzheimer's disease,0.0,False,False,False
36693,PXD017972,Transgenerational long-term effects of the emb...,0.0,False,False,False
36694,PXD041218,Progresses and challenges of Strongyloides spp...,0.0,False,False,False
36695,PXD046030,Structural Similarities on Hymenoptera Allerge...,0.0,False,False,False